export const ParishToCountyMap = new Map([
    ["Hageri khk.", "Harju"],
    ["Harju-Jaani khk.", "Harju"],
    ["Harju-Madise khk.", "Harju"],
    ["Jõelähtme khk.", "Harju"],
    ["Jüri khk.", "Harju"],
    ["Juuru khk.", "Harju"],
    ["Keila khk.", "Harju"],
    ["Kose khk.", "Harju"],
    ["Kuusalu khk.", "Harju"],
    ["Nissi khk.", "Harju"],
    ["Rapla khk.", "Harju"],
    ["Risti khk.", "Harju"],
    ["Ambla khk.", "Järva"],
    ["Anna khk.", "Järva"],
    ["Järva-Jaani khk.", "Järva"],
    ["Järva-Madise khk.", "Järva"],
    ["Koeru khk.", "Järva"],
    ["Paide khk.", "Järva"],
    ["Peetri khk.", "Järva"],
    ["Türi khk.", "Järva"],
    ["Emmaste khk.", "Lääne"],
    ["Hanila khk.", "Lääne"],
    ["Käina khk.", "Lääne"],
    ["Karuse khk.", "Lääne"],
    ["Kirbla khk.", "Lääne"],
    ["Kullamaa khk.", "Lääne"],
    ["Lääne-Nigula khk.", "Lääne"],
    ["Lihula khk.", "Lääne"],
    ["Märjamaa khk.", "Lääne"],
    ["Martna khk.", "Lääne"],
    ["Noarootsi khk.", "Lääne"],
    ["Pühalepa khk.", "Lääne"],
    ["Reigi khk.", "Lääne"],
    ["Ridala khk.", "Lääne"],
    ["Varbla khk.", "Lääne"],
    ["Vigala khk.", "Lääne"],
    ["Vormsi khk.", "Lääne"],
    ["Audru khk.", "Pärnu"],
    ["Häädemeeste khk.", "Pärnu"],
    ["Halliste khk.", "Pärnu"],
    ["Karksi khk.", "Pärnu"],
    ["Mihkli khk.", "Pärnu"],
    ["Pärnu khk.", "Pärnu"],
    ["Pärnu-Jaagupi khk.", "Pärnu"],
    ["Saarde khk.", "Pärnu"],
    ["Tori khk.", "Pärnu"],
    ["Tõstamaa khk.", "Pärnu"],
    ["Vändra khk.", "Pärnu"],
    ["Anseküla khk.", "Saare"],
    ["Jaani khk.", "Saare"],
    ["Jämaja khk.", "Saare"],
    ["Kaarma khk.", "Saare"],
    ["Karja khk.", "Saare"],
    ["Kärla khk.", "Saare"],
    ["Kihelkonna khk.", "Saare"],
    ["Muhu khk.", "Saare"],
    ["Mustjala khk.", "Saare"],
    ["Pöide khk.", "Saare"],
    ["Püha khk.", "Saare"],
    ["Ruhnu khk.", "Saare"],
    ["Valjala khk.", "Saare"],
    ["Äksi khk.", "Tartu"],
    ["Kambja khk.", "Tartu"],
    ["Kodavere khk.", "Tartu"],
    ["Kursi khk.", "Tartu"],
    ["Laiuse khk.", "Tartu"],
    ["Maarja-Magdaleena khk.", "Tartu"],
    ["Nõo khk.", "Tartu"],
    ["Otepää khk.", "Tartu"],
    ["Palamuse khk.", "Tartu"],
    ["Puhja khk.", "Tartu"],
    ["Rannu khk.", "Tartu"],
    ["Rõngu khk.", "Tartu"],
    ["Sangaste khk.", "Tartu"],
    ["Tartu-Maarja khk.", "Tartu"],
    ["Torma khk.", "Tartu"],
    ["Võnnu khk.", "Tartu"],
    ["Helme khk.", "Viljandi"],
    ["Kolga-Jaani khk.", "Viljandi"],
    ["Kõpu khk.", "Viljandi"],
    ["Paistu khk.", "Viljandi"],
    ["Pilistvere khk.", "Viljandi"],
    ["Põltsamaa khk.", "Viljandi"],
    ["Suure-Jaani khk.", "Viljandi"],
    ["Tarvastu khk.", "Viljandi"],
    ["Viljandi khk.", "Viljandi"],
    ["Haljala khk.", "Viru"],
    ["Iisaku khk.", "Viru"],
    ["Jõhvi khk.", "Viru"],
    ["Kadrina khk.", "Viru"],
    ["Lüganuse khk.", "Viru"],
    ["Rakvere khk.", "Viru"],
    ["Simuna khk.", "Viru"],
    ["Väike-Maarja khk.", "Viru"],
    ["Vaivara khk.", "Viru"],
    ["Viru-Jaagupi khk.", "Viru"],
    ["Viru-Nigula khk.", "Viru"],
    ["Hargla khk.", "Võru"],
    ["Kanepi khk.", "Võru"],
    ["Karula khk.", "Võru"],
    ["Põlva khk.", "Võru"],
    ["Räpina khk.", "Võru"],
    ["Rõuge khk.", "Võru"],
    ["Urvaste khk.", "Võru"],
    ["Vastseliina khk.", "Võru"],
]);


export const CountyToParishMap = new Map<string, string[]>([
    ["Harju", ["Hageri khk.", "Harju-Jaani khk.", "Harju-Madise khk.", "Jõelähtme khk.", "Jüri khk.", "Juuru khk.", "Keila khk.", "Kose khk.", "Kuusalu khk.", "Nissi khk.", "Rapla khk.", "Risti khk."]],
    ["Järva", ["Ambla khk.", "Anna khk.", "Järva-Jaani khk.", "Järva-Madise khk.", "Koeru khk.", "Paide khk.", "Peetri khk.", "Türi khk."]],
    ["Lääne", ["Emmaste khk.", "Hanila khk.", "Käina khk.", "Karuse khk.", "Kirbla khk.", "Kullamaa khk.", "Lääne-Nigula khk.", "Lihula khk.", "Märjamaa khk.", "Martna khk.", "Noarootsi khk.", "Pühalepa khk.", "Reigi khk.", "Ridala khk.", "Varbla khk.", "Vigala khk.", "Vormsi khk."]],
    ["Pärnu", ["Audru khk.", "Häädemeeste khk.", "Halliste khk.", "Karksi khk.", "Mihkli khk.", "Pärnu khk.", "Pärnu-Jaagupi khk.", "Saarde khk.", "Tori khk.", "Tõstamaa khk.", "Vändra khk."]],
    ["Saare", ["Anseküla khk.", "Jaani khk.", "Jämaja khk.", "Kaarma khk.", "Karja khk.", "Kärla khk.", "Kihelkonna khk.", "Muhu khk.", "Mustjala khk.", "Pöide khk.", "Püha khk.", "Ruhnu khk.", "Valjala khk."]],
    ["Tartu", ["Äksi khk.", "Kambja khk.", "Kodavere khk.", "Kursi khk.", "Laiuse khk.", "Maarja-Magdaleena khk.", "Nõo khk.", "Otepää khk.", "Palamuse khk.", "Puhja khk.", "Rannu khk.", "Rõngu khk.", "Sangaste khk.", "Tartu-Maarja khk.", "Torma khk.", "Võnnu khk."]],
    ["Viljandi", ["Helme khk.", "Kolga-Jaani khk.", "Kõpu khk.", "Paistu khk.", "Pilistvere khk.", "Põltsamaa khk.", "Suure-Jaani khk.", "Tarvastu khk.", "Viljandi khk."]],
    ["Viru", ["Haljala khk.", "Iisaku khk.", "Jõhvi khk.", "Kadrina khk.", "Lüganuse khk.", "Rakvere khk.", "Simuna khk.", "Väike-Maarja khk.", "Vaivara khk.", "Viru-Jaagupi khk.", "Viru-Nigula khk."]],
    ["Võru", ["Hargla khk.", "Kanepi khk.", "Karula khk.", "Põlva khk.", "Räpina khk.", "Rõuge khk.", "Urvaste khk.", "Vastseliina khk."]],
]);
