import DataTransformer from "./DataTransformer";

const ParishToCountyMap = new Map([
    ["Hageri khk.", "Harju"],
    ["Harju-Jaani khk.", "Harju"],
    ["Harju-Madise khk.", "Harju"],
    ["Jõelähtme khk.", "Harju"],
    ["Jüri khk.", "Harju"],
    ["Juuru khk.", "Harju"],
    ["Keila khk.", "Harju"],
    ["Kose khk.", "Harju"],
    ["Kuusalu khk.", "Harju"],
    ["Nissi khk.", "Harju"],
    ["Rapla khk.", "Harju"],
    ["Risti khk.", "Harju"],
    ["Ambla khk.", "Järva"],
    ["Anna khk.", "Järva"],
    ["Järva-Jaani khk.", "Järva"],
    ["Järva-Madise khk.", "Järva"],
    ["Koeru khk.", "Järva"],
    ["Paide khk.", "Järva"],
    ["Peetri khk.", "Järva"],
    ["Türi khk.", "Järva"],
    ["Emmaste khk.", "Lääne"],
    ["Hanila khk.", "Lääne"],
    ["Käina khk.", "Lääne"],
    ["Karuse khk.", "Lääne"],
    ["Kirbla khk.", "Lääne"],
    ["Kullamaa khk.", "Lääne"],
    ["Lääne-Nigula khk.", "Lääne"],
    ["Lihula khk.", "Lääne"],
    ["Märjamaa khk.", "Lääne"],
    ["Martna khk.", "Lääne"],
    ["Noarootsi khk.", "Lääne"],
    ["Pühalepa khk.", "Lääne"],
    ["Reigi khk.", "Lääne"],
    ["Ridala khk.", "Lääne"],
    ["Varbla khk.", "Lääne"],
    ["Vigala khk.", "Lääne"],
    ["Vormsi khk.", "Lääne"],
    ["Audru khk.", "Pärnu"],
    ["Häädemeeste khk.", "Pärnu"],
    ["Halliste khk.", "Pärnu"],
    ["Karksi khk.", "Pärnu"],
    ["Mihkli khk.", "Pärnu"],
    ["Pärnu khk.", "Pärnu"],
    ["Pärnu-Jaagupi khk.", "Pärnu"],
    ["Saarde khk.", "Pärnu"],
    ["Tori khk.", "Pärnu"],
    ["Tõstamaa khk.", "Pärnu"],
    ["Vändra khk.", "Pärnu"],
    ["Anseküla khk.", "Saare"],
    ["Jaani khk.", "Saare"],
    ["Jämaja khk.", "Saare"],
    ["Kaarma khk.", "Saare"],
    ["Karja khk.", "Saare"],
    ["Kärla khk.", "Saare"],
    ["Kihelkonna khk.", "Saare"],
    ["Muhu khk.", "Saare"],
    ["Mustjala khk.", "Saare"],
    ["Pöide khk.", "Saare"],
    ["Püha khk.", "Saare"],
    ["Ruhnu khk.", "Saare"],
    ["Valjala khk.", "Saare"],
    ["Äksi khk.", "Tartu"],
    ["Kambja khk.", "Tartu"],
    ["Kodavere khk.", "Tartu"],
    ["Kursi khk.", "Tartu"],
    ["Laiuse khk.", "Tartu"],
    ["Maarja-Magdaleena khk.", "Tartu"],
    ["Nõo khk.", "Tartu"],
    ["Otepää khk.", "Tartu"],
    ["Palamuse khk.", "Tartu"],
    ["Puhja khk.", "Tartu"],
    ["Rannu khk.", "Tartu"],
    ["Rõngu khk.", "Tartu"],
    ["Sangaste khk.", "Tartu"],
    ["Tartu-Maarja khk.", "Tartu"],
    ["Torma khk.", "Tartu"],
    ["Võnnu khk.", "Tartu"],
    ["Helme khk.", "Viljandi"],
    ["Kolga-Jaani khk.", "Viljandi"],
    ["Kõpu khk.", "Viljandi"],
    ["Paistu khk.", "Viljandi"],
    ["Pilistvere khk.", "Viljandi"],
    ["Põltsamaa khk.", "Viljandi"],
    ["Suure-Jaani khk.", "Viljandi"],
    ["Tarvastu khk.", "Viljandi"],
    ["Viljandi khk.", "Viljandi"],
    ["Haljala khk.", "Viru"],
    ["Iisaku khk.", "Viru"],
    ["Jõhvi khk.", "Viru"],
    ["Kadrina khk.", "Viru"],
    ["Lüganuse khk.", "Viru"],
    ["Rakvere khk.", "Viru"],
    ["Simuna khk.", "Viru"],
    ["Väike-Maarja khk.", "Viru"],
    ["Vaivara khk.", "Viru"],
    ["Viru-Jaagupi khk.", "Viru"],
    ["Viru-Nigula khk.", "Viru"],
    ["Hargla khk.", "Võru"],
    ["Kanepi khk.", "Võru"],
    ["Karula khk.", "Võru"],
    ["Põlva khk.", "Võru"],
    ["Räpina khk.", "Võru"],
    ["Rõuge khk.", "Võru"],
    ["Urvaste khk.", "Võru"],
    ["Vastseliina khk.", "Võru"],
]);

class ParishToCounty extends DataTransformer {

    transform = (value: string): string[] | null => {
        return ParishToCountyMap.get(value)?.split(",").map(v => v.trim()) || null;
    }
}

export default ParishToCounty;
